### ISSUE TITLE
I'm a newbie | using sublime text3 to run main.jl and fail. How can I do?

### ISSUE THREAD

**Issue by whyLucensisnotavailable** [justinjjlee/SmoothLocalProjections.jl#1]
![feaba8351ca7eddce5b989b1f02d60e](https://github.com/justinjoliver/julia-SmoothLocalProjections.jl/assets/133218989/e716eb3a-2dac-44de-9d0d-5f14608f4edb)

**Comment by justinjjlee** [comment]
Seems like you have not installed relevant packages used in the script. You can follow the bug message and install the packages yet available in your machine.

**Comment by whyLucensisnotavailable** [comment]
Thank You!

Justin ***@***.***> 于2023年5月20日周六 05:28写道：
